# Abstract {-}

Congressional primary elections are widely believed to play a crucial role in the representation of voters in a congressional district.
Many scholars believe that primary competition is the standout reason why classic predictions from formal models of electoral competition---that candidates take ideological positions near the district's median voter---fail to manifest in the real world.
The general election context provides incentives for candidates to take centrist policy positions, but candidates must win their party's nomination before advancing to the general election.
Because primary elections take place predominantly among voters of one political party affiliation, and because those voters tend to hold faithful partisan beliefs across issues, candidates feel more acute incentives to take strong partisan stances on issues rather than moderate stances even amid stiff general election competition.

This story of primary elections and representation is widely believed, but is it true? 
Despite its prominence, the empirical evidence is unclear.
The theory rests on a notion that voters make informed choices in primary elections by consulting their policy preferences and choosing the candidate with the closest policy platform, and candidates position themselves to anticipate this pattern of primary voting.
Past research has been unable to operationalize key constructs in this prediction, or it has operationalized the wrong constructs.
Candidates should take more extreme positions when the primary constituency has a stronger preference for ideologically off-center policy, but studies have not directly measured the policy preferences of partisans within a candidate's district.
Studies instead rely on proxy measures that misrepresent the theory, so the theory goes untested on its own terms.

This dissertation develops and applies new Bayesian approaches for estimating the key construct that has eluded the study of primary politics: the preferences of the partisan constituencies within a district.
I call this construct _district-party ideology_. 
I then apply this measure in two empirical studies that estimate district-party ideology's causal effect on primary candidates' ideological positioning and its moderating effect on primary candidate selection.
There are several contributions for the study of primary elections and quantitative political science in this project.
I establish new data on district-party preferences, provide theoretical clarity about hypothesized causal relationships, and advance the causal rigor of observational research on primary elections.
This project also establishes and exemplifies a Bayesian framework for estimating causal effects, which is valuable for estimating causal effects using structural models and data generated from measurement models but undeveloped in political science.
