# Data and Code

This project is entirely open source and managed with Git.
Source code for all analysis (`R` and `Stan`) and writing (`Rmarkdown`) is available on Github at <https://github.com/mikedecr/dissertation>.
Data are available on Box at <https://uwmadison.box.com/s/paivoulvu3jw9ze3nqq4c6vbrcexqseh>.
This document was produced at `r Sys.time()` with the source code at the following commit: 

```{r echo = FALSE, include = TRUE, cache = FALSE}
# I've set eval=FALSE to ensure Travis-CI can run
# if you're not using Travis-CI, then eval=TRUE will be fine
library("git2r")
if (in_repository()) {
  summary(commits()[[1]]) 
} else { 
  message("We are not in a git repository") 
}
```


The computational environment that was used to generate this version is as
follows:

```{r session-info, eval = TRUE, echo = TRUE, include = TRUE, message = FALSE, warning = FALSE, cache = FALSE}
library("tidyverse")

installed.packages() %>%
  as_tibble() %>%
  pull(Package) %>%
  devtools::package_info() %>%
  as_tibble() %>%
  select(pkg = package, version = ondiskversion, src = source) %>%
  print(n = nrow(.))
```


