---
# for reference:
# - Mahr: <https://github.com/tjmahr/dissertation/blob/master/index.Rmd>

title: "Do Primaries Work?"
subtitle: "Nomination Politics and the Representation of Local Partisan Preferences" 
author: "Michael G. DeCrescenzo"
date: |
  | `r if (knitr::is_latex_output()) "IDK yet" else if (knitr::is_html_output()) stringr::str_glue("Compiled {format(Sys.time(), '%B %d, %Y: %H:%M')}")`
#  `r format(Sys.time(), "%B %d, %Y: %H:%M")` 
site: "bookdown::bookdown_site"
github-repo: "mikedecr/dissertation"

# annoying top-level LaTeX control
documentclass: memoir
fontsize: 11pt
geometry: "left = 1.25in, right = 1.25in, top = 1.25in, bottom = 1.25in"
bibliography: assets-bookdown/thesis.bib
csl: assets-bookdown/ajps.csl
---



```{r helpers-index, include = FALSE, cache = FALSE}
source(here::here("assets-bookdown", "knitr-helpers.R"))
```

<!-- BEGIN FRONTMATTER CONTENT -->

<!-- HTML abstract -->
`r if (knitr::is_html_output()) include_text("00_abstract.rmd")`

<!-- TeX: roman numbering, not on title page -->
`r if (knitr::is_latex_output()) include_text("00_frontmatter.rmd")`





<!-- R E N D E R I N G 

NOTE: if you move writing into subfolders: 
      setwd(here::here("writing")); render_*(...); setwd(here::here())

-->

```{r render-GITBOOK, eval = FALSE, cache = FALSE, include = FALSE}
bookdown::render_book(
  input = "Index.Rmd", 
  output_format = "bookdown::gitbook"
  # , new_session = FALSE # knits IN SESSION
)
```

```{r serve-book, eval = FALSE, cache = FALSE, include = FALSE}
bookdown::serve_book(
  dir = here::here(), 
  output_dir = here::here("_book"), 
  preview = TRUE, 
  in_session = TRUE, 
  quiet = FALSE
)
```

```{r stop-server, eval = FALSE, cache = FALSE, include = FALSE}
servr::daemon_stop()
```

```{r render-PDF, eval = FALSE, cache = FALSE, include = FALSE}
bookdown::render_book("Index.Rmd", "bookdown::pdf_book")
```



```{r render-HTML, eval = FALSE, cache = FALSE, include = FALSE}
bookdown::render_book("Index.Rmd", "bookdown::html_book")
```



```{r render-preview-CHAPTER, eval = FALSE, cache = FALSE, include = FALSE}
bookdown::preview_chapter('020_model.Rmd')
```

```{r render-interactive, eval = FALSE, cache = FALSE, include = FALSE}
rmarkdown::render(here::here('020_model.Rmd'))
```





<!------- TO DO ---------
- Fix this git stuff
------------------------->


<!-- git info  -->
```{r git-info, include = FALSE, cache = FALSE}
branch_name <- system("git symbolic-ref --short HEAD", intern = TRUE)
commit_hash <- system("git log --pretty=%t", intern = TRUE)[1]
commit_msg <- system("git log --pretty=%s", intern = TRUE)[1]
```


<!-- appears on page 1 if HTML -->
```{block, include = knitr::is_html_output(), cache = FALSE}
Commit ``r commit_hash`` on branch "``r branch_name``":

    `r commit_msg`
```





<!------- TO DO ---------
- License
------------



