---
title: Overall thesis notes
---

# Near-Term Agenda


- opening remarks
    - Thanks all.
    - Project evolved from substantive w/ methods chapter, to more of a methods-focused project as my interests evolved and my career ambitions shifted.
    - Tried to package the methods approaches in ways that make it obvious how they enable important substantive contributions that we couldn't quite obtain without those innovations.
    - Key substantive contributions: 
        - Overall:
            - Theory-testing rather than theory development, which is still science.
            - we have this story that we tell that comes from the research on polarization about ideological primary electorates, candidate positioning, and primary election outcomes—the SPD—but tests of the theory have these important measurement shortcomings, and therefore theoretical shortcomings, but we can improve on our understanding using certain measurement and modeling approaches that have only recently been popularized in political science.
        - Ideal point measures
            - create district-party ideology estimates around which the project is substantively based. 
            - past theoretical development in this area says that the preferences of the partisan base impose a different positioning incentives from the incentives imposed by the district vote, yet past research really only ever uses the presidential vote to measure voter preferences, which papers over the whole argument underlying this theoretical story in the first place!
            - chapter 1 makes a theoretical argument that presidential vote data cannot proxy district-party base preferences like, which justifies the ideal point model that I create in chapter 2.
        - Empirical applications
            - ch 4: Now that we have a measure of district-party ideology that is distinct from the presidential vote, how do we think it behaves in a causal structure alongside district voting, and what can we do about it from a research design standpoint for estimating the causal effects. There are definitely methodological contributions here with the nitty gritty details of sequential g, but I don't want to brush too quickly past the fact that the theorizing about the causal structure and what that means for causal effects is, I think, an important theoretical and substantive flag that I'm putting in the ground about the way we study primaries, which other studies have been less careful to implement in their empirics. This chapter finds that district-party ideology appears to be actually a much more coherent influence on candidate positioning than the district presidential vote. incumbents, challengers, and open candidates all respond to the party base, but they don't all respond to the presidential vote. That's pretty important, I think it presents a new puzzle for future work to look into. I also find some new evidence on primary rules that runs against some of the prevailing wisdom in this literature. Most studies find no relationship at all between candidate positioning and primary rules, but I do find that candidates under more closed systems are more elastic to district-party preferences than candidates in more open systems. So it's not about extremism per se but responsiveness
            - Ch 5: Candidates behave in line with the SPD, but what about voters? The underlying spatial model of voting matters for studying primary voting, since the SPD is a spatial theory of sincere voting. So the real substantive push in this chapter is looking for evidence of that utility optimum, which is important for identifying whether primary voting appears to be ideological–is there some preferred point for a district-party group–and building a research design that identifies heterogeneity in that utility optimum in different districts with different partisan base preferences. I find evidence that's weakly consistent with the idea that candidate ideology matters for primary voters, but the data don't support the notion that those ideological preferences are highly specific in the way that the SPD would predict. Primary voters appear to favor candidates who represent the ideological core of the party, but from one district to the next, we don't really see primary electorates engaging in fine-grained ideological discrimination between candidates.
    - Methods contributions, 3 big ones in order from least to most important.
        - 1. Ideal point model. This is important to the project, but it's probably the least _unique_ methods contribution here. The group IRT modeling technology that I use is adapted from other recent work, so I can't take credit for inventing it, but I do some things to the model to adapt it to measure district-party ideology. Most methodologically distinct elements of the ideal point model are pretty in the weeds of applied Bayesian modeling, but I think they're important because they represent advances in Bayesian modeling that aren't really articulated in any single place in political science. Recent innovations in prior distributions, talking about how the model itself is prior information, the hierarchical model parameterization and how it relates to computation, are all really important lessons for doing applied Bayesian stats in political science, but this is all stuff you can't learn about in PS work. There isn't really any resource for a PS audience that explains these things in the same level of thoroughness as I do, so that's an important contribution to highlight on the methods front.
        - 2. Bayesian approach to causal inference. This chapter probably feels like a bit of a detour to the main road of the project, but I felt like it was important to articulate and explain because, if I were to just proceed with Bayesian causal modeling in chapters 4 and 5 without really explaining what was going on, it would have felt pretty out-of-nowhere for the reader, I think. But playing around with Bayesian causal inference is something I spent a lot of time in the program doing, I thought it offered important benefits for this project, so I thought it deserved an explanation to really lay out what's the big idea here. It is a detailed chapter that discusses some pretty hairy aspects of Bayesian modeling, such as implied priors and so on, but I think that those discussions are really important for explaining what the deal with BCI really is. The purpose is to show how the Bayesian "version" of some model that you might use off the shelf for causal inference will inevitably have some pretty unexpected prior behavior that the researcher would likely find disagreeable, so I thought it was pretty impossible to talk about Bayesian causal inference without clearing up how important and frame-shifting some of those lessons are for understanding what my approach is really doing. 
    - 3: The most important, and I think most broadly applicable methodological push in the project, is the use of graphical causal models to theorize about these research questions. This literature on primaries, and a ton of observational work more broadly in political science, uses selection-on-observables research designs with regression-based estimation approaches. But it isn't especially common to see run-of-the-mill regression studies like chapters 4 and 5, and take their causal claims seriously. Formally define the causal quantities, the assumptions, which adjustments are req'd, which things should we NOT control for, and so on? The more I learn about modern causal inference, the more opportunities I see in other folks' research to be more explicit about the causal structure, linking that structure to our statistical methods, making sure we aren't giving regression controls a causal interpretation. These are things that I think the whole field could be doing better at, and it's something that this particular literature doesn't have a lot of, So I really wanted to lead by example and have that style of observational work be an important contribution for this project.


Could I read more things?





- Document
    - [ ] Title page
    - Appendix 
        - [ ] chapter numbering (and in-text references)
        - [ ] table/fig numbering
    - Colophon
        - fix url style
        - sessionInfo
    - All ref check
    - cut "in order"
    - contractions
- ch 1
    - preview findings
    - fix ML stuff
- ch 2: 
    - fake data thetas; how is the standardization being done...?
    - is income logged?
    - revisions:
        - do we want pres vote?
        - ANES 2012 and 2014
- write ch 3
- ch 4:
    - revisions:
        - run MCMC on fixed theta
        - send alex data and code
- ch 5:
    - Fix DAG figure
    - revisions:
        - ideal point prior
        - add a constant to spline (fix MCMC?)
        - mcmc all models


Next week: zoom link test


scheduling

- Barry: no MW 3:30-5 
- Ken: TR 9:30–11, 2:30-3:45  (could be recorded)
- Alex: W 1:30–3:30, MW 4–5:30
- Mike: M 12-1, M 3-4, TR 11–12:15, R 2-3
- No APWs (19th OK!)
- W 11-1 faculty meetings
- Ellie: no 12th, no 13th before 11 am, W 8:30-10-15, 2:30-4:30 (afternoons are movable if necessary), Th 1-2:30 (movable if necessary)


# Meetings

## Qs for Barry

Lit questions

- How to characterize your disagreement w/ A.S.S. on incumbents, challengers, open seats.
    - Burden: incumbency is insurance
    - Ans: incumbency reflects selection, challengers/open must innovate
    - Groseclose: challengers are differentiating (formal arg) because they lose on non-policy
- Variance weighting of ideal points
    - King/Herron EI/WLS problem
- utility optimum
    - James Adams quadratic
    - Adams/Dow directional vs. proximity voting


Things I don't really plan to get to:

- Lit:
    - adams
    - more detailed boatright
- potential new data sources: 
    - is district in NAES 
    - When did CCAP run 



- what else explains the gaps? race/maj-min?



## Qs for Alex

CLOGIT:

- discussion of the linear transformation and the spline
- causal inf integrals


G model:

- identifiability:
    - ideal points
    - residuals?
- what's the deal w/ variational

Statistics notation in general

- subscripting is for the variable, no subscript is for the value




Neural net:

- what's the treatment?
- multivariate Gaussian process

- Sparsity-inducing priors as an approximation to "dropout"
- GP as generalization of neural net?


- best linear predictor (argmin MSE) in a binary treatment case?
    - is this just an in/out of sample thing?
- what does it mean for a model to estimate a regularizing prior?
    - beta ~ normal(0, alpha); alpha ~ cauchy(0, tau), tau ~ ?
    - Is this just overfitting, or what?
    - I'm doing LOO to guard against model complexity
- priors and likelihoods
    - relating arithmetic mean to beta-binomial model:
        - the arithmetic mean the same as the MAP under...beta(1, 1) prior?
        - how does the beta(.5, .5) prior relate to nonparametric estimation of the proportion?


# Reading

##  Methods

Bayes and causal inference

- Maclaren identifiability
- Zigler et al 2013: two stage Bayes
- Bayesian causal inf (Oganisian, etc)
- other cool hypothesis reframing stuff
    - TOST equivalence test of assumptions
    - Caughey NPC, beyond sharp null
- design uncertainty
- Gelman King (Bayesian causal inf in political science?)
- Pearl: "half-Bayesian"
- bayes holes
- kang whoever demystifying double robustness
- imbens rubin 1997
- king measurement error
- bayes do-calc papers
- rubin 1984: bayes frequency
- objective bayes back and forth


Neural Nets

- residual debiasing (athey et al)
- Bayesian view/uncertainty
- Regularization approaches
    - Simpson et al. "Penalizing Model Complexity"
    - what is "dropout"
    - can I approximate dropout
    - sparsity priors, regularizing priors, etc.
- Discrete choice models
- Model avging over multiple models
- Hartford et al. counterfactual prediction


Broad ML

- tree models for p.s. (montgomery et al)



Meta-Analysis

- ranefs meta-analysis
    - the Borenstein estimator seems deterministic? is this obtained by an infinite variance prior?
    - what choices are we making with the Bayesian (Rubin) view? compromise between flat prior and spike prior?
    - std.err of estimator is the average wrongness from truth, but we don't know what side of the wrongness we're on



## Ch 1 and other design stuff

Primaries and representation:

- cited in brady, han, and pope
    - A.s.s.
    - fiorina 1999
    - galderisi, ezra, lyons 2001
    - hacker/pearson 2005
    - MPR 2006
    - Bradyand Schwartz1995
    - burden 2001
    - francis et al 2004
    - gerber/morton 1998
    - schmidt, kenny, morton 1996
- evidence of primary extremism
    - presidentials: Norrander1989; Polsbyand Wildavsky1978
    - extremism of presidential delegates: McClosky, Hoffman,and O'Hara 1960; Soule and McGrath 1975; Stone and Rapoport 1994
    - SPD in primaries: Aldrich 1995;PolsbyandWildavsky2004; Schlesinger1991
- Brady/Han/Pope SPD:
    - primary preferences must differ
        - Senate: BradyandSchwartz1995; Francis etal. 1994 ; GerberandMorton1998; Schmidt,Kenny,Morton 1996; 
        - House: scant evidence
    - they must present a _credible threat_
        - general election vote losses principle (Canes-WroneB,radya,ndCogan2002) should apply to the primary, no?
        - moderate candidates _attract_ primary threat (endogeneity)
        - costs of flip-flopping on candidate reputations, clarity of positions: Alvarez1997
- Burden 2001:
    - candidates view of the world vs. voter view: be on your best behavior to not give opponents ammo and fend off challenges. Voters not noticing is actually a _best-case_ scenario.
    - "As long as legislators think that positions matter, then researchers should treat them as though they do"
    - overreaction to the circumstances on the ground is actually equilibrium! So the "unreasonableness" of legislator behavior in the face of voter ignorance or apathy is actually the equilibrium path that the legislator wants to be on, otherwise they could be caught behaving badly and have their voters be made aware.
    - some evidence that legislators are more extreme when they have primary challengers


Formal models that explain divergence:

- Aldrich 1983,
- Alesina 1988,
- Calvert 1985
- Wittman 1977
- Cox 1990: centripetal and centrifugal

- Districts and representation
    - Ensley AJPS, public choice, district complexity/heterogeneity

Other things to come back to:

- porter and treul
- Desmarais et al EPN




# Data agenda

- check on primary laws again, potentially resolve with Barry
- dynamic model, past data




# Modeling agenda


## Neural Net

- choose covariates in hidden layer, or hierarchical coefficients
    - might not be worth it but hey that's ML baybee!
- Combining subposteriors
    - Kernel estimator
    - GP estimator
    - firefly MCMC
- parameterization: do we need covariates in stage 2
- identifiability
        - identifiability paper
        - run for longer, with thinning
        - simulate fake data to see that predictions work even if the parameters look bad

# Writing Thoughts:

Theory: 

- how to set this up as falsification focus rather than verification focus
    - severe tests


# The Wild west


- Alex:
    - More practical question: what's the best strategy for regularizing a in a bayesian causal workflow

    - posterior ideal points
        - estimate MVnormal for ideal points
    - identifiability
        - identifiability paper
        - run for longer, with thinning
        - simulate fake data to see that predictions work even if the parameters look bad
    - two stage
        - send alex paper
    - _Check notebook_
    - identifiability/comparing chains in NN
        - particle filter/genetic algorithm thing to resample chains according to relative posterior probability? 
        - get a marginal likelihood for each chain (harmonic mean estimator, kind of problematic (newton-raftery)), supposed to be 1 number across chains, but you can hack it by looking across chains.
        - or bridge sampling for "approximately correct" marginal likelihood estimator
        - estimate a separate model for different assumptions, use marginal likelihood to reweight estimates
    - how to understand "BART is a prior"?
        - is it just to say that all models are priors for (new) data?
    - conditional logit:
        - is this the right direction to go?
        - All predictors are differences from baseline, or no? just the SUM of one utility is normalized?
        - can size of choice set vary across sets?
        - can the choices themselves be different across sets (have different sets of features)? Doesn't seem like it has to, it's just that I'm imposing fixed coefficients
        - what's the deal with IIA? Choice utility (or probability) ratios are unaffected by presence of additional choices?
        - making it in stan:
            - <https://github.com/stan-dev/rstanarm/blob/master/src/stan_files/functions/bernoulli_likelihoods.stan>
            - <https://github.com/stan-dev/rstanarm/blob/master/src/stan_files/bernoulli.stan>
    - Regularization-induced confounding in a neural net?
    - How to think about cross-validation in Bayes context?
        - how to even think about regularization in a neural net?
        - do I fit several models and only predict for units not in the model?
        - _weird how this is probably how things should **always** be done?_
- Barry:
    - check primary candidate quality
    - possible to scrape candidate quality for primary candidates from: Ballotpedia, FEC, Open Secrets
- Ellie:
    - send ch 2


# Reading

## For design

- [ ] Desmairis et al. AJPS
- [ ] read Hall-Thompson
- [ ] Hirano and Snyder
- [ ] Langella and Rogowski
- [ ] Hill
- [ ] Thomsen
- [ ] Achen–Bartels (Realists) lit review
- [ ] Achen critique of Miller and Stokes (Lewis and Tausanovitch)
- [ ] alvarez nagler (conditional/multinom choice)
- [ ] Snyder team old papers


## for thinking

- [ ] read Grimmer's VI paper
- [ ] read Bailey ranefs
- [ ] ranef distribution misspecification
- [ ] read explaining fixed effects
- [ ] Kubinec fixed effects
- Conditional choice models
- Bayesian Neural Nets (might solve choice model problem)


## for writing

- 1. Theory
    - conceptual/term clarity in the beginning
        - who are "partisans" in my groups? (primary voters?)
        - What is "district partisanship" vs. policy ideology?
    - Definition of representation 
        - I only have ideology, not a 1-1 measure of candidate issue congruence or government policy congruence
    - Big view:
        - When would primaries _not_ work? How can you reframe the question to focus energy?
- 2. Model
    - incorporate earlier Barry edits (symlinked)
- 3. Causal Inference 
    - arguments in favor: integrating a loss function over a posterior distribution
    - lots you can read in the Aronow/Miller book!
- 4. Positioning
    - "strategic" vs. sincere "representation" with DIME scores


## for analysis

- Ch 4;
    - Justify ML in theory:
        - Two-stage modeling for selection
            - regression weights
            - regularization-induced confounding
        - Functional form
            - we don't know the relationships between covariates
            - we can actually get around more difficult LIKELIHOOD assumptions with sufficient functional agnosticism w/r/t covariates
    - Empirical demo of problems?
        - Justify ML using RMSE in predicting an exposure?
        - In vs. out of sample performance
    - Decide about two-stage modeling
    - Covariates
        - include other district
        - more polarization in parties -> what does this do to positioning?

## for data

- Thomsen primaries data
- Fix 2010s poll data (multinomial response, midpoints, **barry**)
    - see Stimson notes
    - also Ansolabahere, Rodden, Stewart public IRT
- Gather 2000s poll data
- How sensitive are the ideal points to item inclusion? (cross-validate?)
- Discuss weighting more?
- Secondary data:
    - party nationalization
    - hill/tausanovitch
    - seth hill individual ideal points
- Stimson and thermostat model
    - how he deals w/ multiple polls, missing data
    - also dichotomization



# Project-level tasks

- [ ] clean agenda
- [ ] Model excerpt to Ellie
- [ ] Wagner







# Comments to sort

- Devin:
    - Where do informal party networks enter the causal graph that I'm positing (Ch 4?)
    - Where is incumbency in the Ch 4 graph?
    - We care about the full effect and the direct effect.
- Evan:
    - who votes in primaries? ideological differences? What do we know about this?
    - Open/Closed primaries?
- Rochelle: 
- Blake: 
    - Measure the incidence of challengers within district-party over time. Are there districts that have a stronger history of challengers? What would this matter? (outward pressure?)
- Ken:
    - we care about the distance between parties/candidates in the same district. 
- Dave: 
    - simulate individual-within-district distribution to compare to the "true distribution of preferences" like Fiorina et al.
    - Show IRFs to tell us which issues are most informative.
    - (List of items; status quo coding? "stay the same" is a conservative coding?)
- Ellie:
    - who is a partisan? are we talking leaners?
    - The uncorrelatedness is worth interrogating more (hierarchical coefficients, build MNorm prior)
    - Power calculation (how to even think about this? stress test the simulation?)
- Barry, what's the "stated purpose" of primaries
    - Entry point is primaries and polarization, but there could be more
    - Citizens? Not just citizens. Constituents? Put definition in chapter 1.
    - what are the Dime scores, what are the details, etc.
    - Candidate "status" vs. incumbency status
    - DIME is an acronym, maybe call them CF score
    - primary institutions
        - timing of the primary. Things that bring people to the primary, presidential / gubernatorial primaries affecting turnout, which could have down-ballot effects
        - Rosenstone Hansen 1993 model of timing and turnout
    - margin histogram in the rank plot
        - ggplot
        - Jackman who's the most liberal senator
    - Selection bias in the CFscores
        - make an argument from the literature about where these things are going
        - Danielle Thomsen?
    - VoteSmart data from Rogowski





# misc readings (sort)

- Devin email
- Daron Shaw thermometer dimensions
- Bafumi Gelman correlated ranefs/ what are they
- Between/within estimators for causal inference
- DAGs for fixefs/ranefs
- Algorithmic covariate selection
    - Books at home
    - Justify covariate adjustment w/ cites
- Bailey ranefs/incidental parameters (get this 100% right)




# Model questions:

- including the group-level means of lower-level covariates as a way of absorbing correlation?
- what about pooling toward something not normal?
- Dynamics:
    - biannual estimate, pool within decade
    - each new redistricting is a new set of things
    - Coefs remember time, districts don't
- Weighted likelihood
    - can we calculate weighted $s^{*}$ without going through $\bar{y}^{*}$
- Notation questions
    - notation for the hierarchical model and cell weights? i in some set? s[g]?
- [ ] identifiability in heteroskedastic model


# leftover notes

Data things 

- Adler data (codebook_district_data.pdf)


_Never did finish sending people that new table of contents._


Keep organizing this...


- **Theory/Writing**
    - [ ] candidates fear "idiosyncratic" issues
    - [ ] cite bailey for ranef approach (incidental parameters problem)
    - [ ] vector form covariates in model math section
    - [ ] more cites in model chapter
        - Londregan
    - [ ] what's the deal with equal bill locations?
        - alpha = 0
        - beta also = 0?
        - there are also other ways to get alpha = 0 that aren't equidistant 
    - [ ] first references: MCMC, IRT, SPD
    - [ ] is the "zero point" the "center" of ideology
    - [ ] mimic Stimson's dichotomization
        - see also Ansolabehere, Rodden, Snyder
    - [ ] where else could we do this (measurement scales)
- **Data**
    - [ ] 2016 primary data
    - [ ] BC individual data merge
- **Code**
    - [ ] LICENSE
    - [ ] clean data in `data/_clean` on Box
    - [ ] rred and dblue from R 4.0 palette
    - [ ] helper to grab most recent MCMC
    - [ ] dir paths go into a modular file?
    - [ ] same cache path for pdf/html (less storage)
        - look up bookdown docs on this
        - code idea is in `knitr-helpers.R`
    - [ ] factors/index for groups, items, states, etc. aren't sorted 
        - [ ] go into combine-data, create a rationalizable system
        - [ ] rerun models for 200/100 and then 2k/1k
        - [ ] fix any post-hoc fixed is posteriors.R (crosswalk)
    - [ ] party-varying sigmas
    - [ ] does every parameter have a prior
    - [ ] Fix linstat runs
        - [ ] save stderr and stdout separately
        - [ ] mac access to linstat files
    - [ ] margin histograms for ideal points?
    - [x] which params can we avoid saving (in simulation)?
    - [ ] hack to the end of the simulation exercise
    - [ ] simulation: within-district variance should be an afterthought after the distribution of averages...
        - variance within group should be greater than between
        - does this mean that the exercise is dumb?
    - [x] log1m/log1p functions for probit link
        - doesn't need this?
    - [ ] weighted data likelihood
    - [ ] offline mathjax
- **Big view**
    - [ ] reinterpret all questions as interview questions or news questions rather than as job talk questions



# Ongoing

- *Immediate agenda*
- *Model*
  - [x] survey algo
  - [x] algo snippets
  - [x] design weights
  - [x] model identification
    - [ ] what abt left-bias?
  - [ ] what abt items w/ a middle response? (currently NA? what's closer to SQ?)
  - [ ] CCES Data
  - [ ] ANES data
  - [ ] Roper data
  - [ ] research covariates
    - [ ] tag covariates as d_, s_, r_ ... etc.
  - [ ] dynamics
  - [ ] Custom non-integer binomial likelihood
- *Primary/Elections Data*
  - [ ] Boatright
  - [ ] New Dime
  - [ ] Thomsen/Treul
  - [ ] Hassel
  - [ ] Hernson
  - [ ] Overlap
  - [ ] State primary data (Rogowski and Langella, Masket et al 2014)
    - [ ] Institution (caucus? election?)
    - [ ] Convention screenings? (Barry?)
    - [ ] openness
- *Reading*
  - [ ] Boatright
  - [ ] Boatright edited volume
  - [ ] Tons of papers on my laptop
- *Writing*
  - [ ] write argument chapter
  - [ ] write model chapter
  - [ ] Secondary data analysis for theory-building (have to read)
  - [ ] AFTER READING draw graphs! A chapter for graphs? Or graphs in each chapter?
- *Aesthetics*
  - [ ] fix title page
  - [ ] unify section styles with chapter styles
    - bold Fira?
    - how to deal with bold section/regular chapter?
    - what can you look at for inspiration?
  - [ ] integrate w/ Buckydown






# Barry 10/12

- Data
 + states
  * [ ] primary type (Rogowski and Langella, Masket et al 2014)
  * [ ] primary institution
  * [ ] pre-nomination conventions
   - Barry may have SOME stuff
 + candidates
  * [ ] num. house seats vs primary races
  * [ ] districts w/ competitive race
  * [ ] NOMINATE: party switches, death and retirements
   - check double districts, lowest ICPSR number is the 
   - if the member served previously, they would have an older ICPSR number
   - who's missing from DIME
   - Sara Treul's data on primaries
 + secondary theta
  * [x] email Caughey/Warshaw
  * [ ] Seth Hill
- Model
 + setup
  * [ ] weighted binomial (input?)
  * [ ] dynamic
  * [ ] issue priors
 + testing
  * [ ] relaxed priors (rank order?)
  * [ ] real data
  * [ ] prior predictive check
  * [ ] posterior predictive check
- Writing
 + [ ] just start in on Chapter 1?
 + [ ] Rmd the simulation
   + static homoskedastic? heteroskedastic?
   + dynamic heteroskedastic
- Designs
 + Redistricting
  * depends on fineness of ideal pt data
  * Crespin, Jamie Carson, GIS overlap/changing lines, where is variation coming from (e.g. within states)
 + primaries vs caucuses


If we meet in a week: 

- read Sarah Treul
 + still do more of that
- Seth Hill
 + *keep reading*
- Investigate Boatright data
 + *downloaded primary data*
 + *reserved or requested three books on primaries*
- Investigate conventions data
 + *DO*
- Coverage of PP data, DIME
 + *DO?*
- Poll data (investigate CW code, Lax and Phillips)
 + *keep chugging*
 + *clerically organizing their work*
 + *looking at the code*
- meet Kang
 + *investigate him in advance of the 7th*
 + *investigate which group is bringing him in, (Rob Yablon?)*


Goals for next week:

- Roper and Lax/Phillips, Caughey and Warshaw
 + good to find out the scope
- think about missing data across firm
    + is Stimson a model for dealing with missing data across polls
- vote smart or VoteView or Shor scores for linking giving patterns to policy content
  + more survey cleaning (A.S.S. paper)











