---
title: Archive of things done
---

22 September

- [x] simulation: should discrimination be "identified" exp(sum(log))
    - For the "first-check dissertation version," YES
        - we want the ICCs to look the same
    - for intense stress-testing, we want NO...
        - priors should be wide but the model will hone it in

16 September: 

- [x] export simulation .Rdata (for rmd)
- [x] tweak MCMC tuning params (adapt_delta, max_treedepth)



Aug 19:

- [x] Standardize chunk opts for each .Rmd file
  - source an .R file rather than duplicate chunk opts code per file

Aug 27, 2019:

- [x] rename model subfiles



Aug 10, 2019: Model identification changes

- [x] fix local toolchain for Stan
- [x] run test (sim) models
- [x] see if ideal points look sane without any post-processing
  - *they look very left-shifted*
- [x] git push to remote
- [x] run real models on SSC
- [x] evaluate item-ID posterior samples
- [x] stash any non-model changes
- [x] merge model-identification -> dev
- [x] apply non-model stash on dev


