---
title: thesis - literature notes
---


# To read:

- Gerber Morton 2001
- primary reform:
    - Fiorina, Abrams, Pope (2006)
    - Mann and Ornstein (2012)
- primary voters:
    - Geer 1988
    - Norrander 1989
    - Sides et al. 2017



# 1. Theory


## Primary causes of polarization

- Voters are polarized:
    - Evidence in favor:
        - Hill (2015)
    - Evidence against:
        - Sides(?), Vavreck, Warshaw
    - tbd: 
        - Geer 1988
        - Norrander 1989
        - Sides et al. 2017
    - background:
        - sorting? Is this good evidence?
        - or "conflict extension" 
        - or "ideological polarization"
        - or "affective polarization"/"negative partisanship"
- Closedness:
    - Evidence against: 
        - McGhee et al (2014); 
        - Rogowski and Langella (2015)
        - Ahler et al. (2016) top two CA
        - Kousser et al. (2016) top two CA
        - Hill (2015)
    - For? Gerber and Morton (2001)?
- Low turnout / more active partisan involvement?
    - should be worse in more closed primaries
    - No obvious relationship:
        - Thomsen (2017 WP; update) no clear pattern with what pops
        - Hirano et al (2010) Senate

## Non-primary reasons for intra-party extremism:

- Extremism is a loss-minimization tactic for legislators:
    - McCarty et al: Geography, Uncertainty, Polarization:
        - in a moderate district, we have less info about the location of the median voter, so weak incentive to offer moderate policy platform
        - more heterogeneous voters -> more polarized legislators
    - Broockman: Approaches to policy representation
        - voter "extremism" is usually consistency. Moderation is "crazy uncle"
        - legislative polarization is how they "bet the average"




# 2. Model

models: 

- Park et al, lax and phillips, issue MRP for states
- Warshaw and Rodden, issue MRP for congress and state senate
- Tausanovitch and Warshaw, IRT MRP (ideal point for a "type")
  + heterogeneity using the variance in the cell predictions within state?
- Caughey and Warshaw, group MRP


TW and CW both appear to have state party IRT estimates ready to go? 

- validation?



# 3. Bayesian Causality

Ratkovic 2019: Rehabilitating the Regression

- a regression method for modeling treatment and the response
- sample 1: estimate heterogeneity in treatment as f(X).
- sample 2: estimate covariate relationships to treatment and outcome as f(X), with heterogeneities
- sample 3: estimate treatment effect controlling for combo of confounding and heterogeneities



generalized propensity score modeling:

- Consider a partial linear model $Y = θz + g(x) + e$, which is intended to represent a model where we estimate the effect of Z on Y with some "flexible" function that controls for confounders X
- For several reasons we are worried that "even under ideal circumstances" the coefficient θ does not capture the causal effect of Z
    - either heterogeneity in $Z | E[Z | X]$ ("regression weights", Aronow and Samii 2016)
    - If you use regularization to estimate flexible function $g()$ this would directly confound the statistical expectation of $θ$ ("regularization induced confounding") that is worse with stronger underlying confounding in X or stronger regularization schemes in estimation of $g()$
- Both problems suggest workarounds using propensity score models
    - directly estimate propensity scores, calculate regression weights (Aronow and Samii)
    - "Neyman orthogonalization" or "cross-fitting" to separately estimate g() and Y(z) using a split-sample approach. This forces an orthogonalization of Z and g() through an implicit residualization in the multistage model (controlling for the propensity in the second stage). 
    - My treatment of interest is continuous, so binary propensity models don't work for me. 
- Continuous propensity score modeling (Hirano and Imbens book chapter)
    - Estimate E[Z | X], 
    - Determine p(Z) for potentially continuous Z (example uses a parametric model)
    - E[Y(z) | p(z)] is estimated by averaging (integrating) over the propensities within one treatment status. This is basically IPW but with a continuous treatment using the integral to generalize the weighted averaging.
- Chernozhukov et al: Double ML
    - Theoretical & application paper to demonstrate statistical properties of the cross-fitting method to get around the regularization induced confounding.
    - Pretty complicated and above my reading level so I don't know how much to dig into this.
- Carvalho et al. paper 




# 4. Positioning

Snyder & Ting 2002: informational party brands

- party brands are an average of candidates ideologies (unobserved by voters)
  + why candidates, not voters?
- candidates join a party as f(district median) and p(win)
- less candidate variance -> more informative signal
- divergence when party can't control its membership (can't screen or low cost to entry)
  + convergence when parties are able to control
  + geographic variation is all correlated candidate information, not state-party offsets from national party
- Why divergence?
  + parties have to endogenously select a platform to convince candidates to run
  + if the benefit of office is high, convergent positions attract too wide a distribution of candidates -> less information for voters -> less benefit for parties



Snyder & Ting 2003 (formal): Roll calls 

- motivating assumptions:
  + extreme incumbents are vulnerable to centrist challengers (general)
  + *challenger ideology less responsive to district ideology*
    * elections are a selection on representativeness
  + extremity is punished in general election vote share, controlling for district partisanship
- find 



Snyder and Ting 2008: Interest groups and control of legislators



Hirano, Snyder, Ting 2009: Distributive politics w/ primaries

- conditions for when candidates owe what to which groups in the electorate
- without primaries, moderate voters are better off
- with primaries, candidates must overcome primary hurdle (what does this look like?)
- as core voters become more extreme on non-transfer (social) issues, the candidate can offer less transfer to the core because the core cares more about winning
- Valence advantages (e.g. favorable midterms?) allow candidates to transfer more to core, less to swing


Snyder and Ting 2011: Electoral Selection w/ Parties and Primaries



Hirano and Ting 2014: Direct and Indirect representation

- politicians direct transfers to interest groups when the marginal electoral benefit of the group's loyalty is high



Ting, Snyder, Hirano 2018: Primaries and public goods

- private vs public goods for moderate and extreme groups



**Questions for Ting**

- my thesis
  + Primaries vs general elections as positioning incentives
  + Strategic dilemma between primary and general voters
  + Too much for the general voters, not enough for the primary, leads to threat of primary challenge
- Explaining non-convergence
  + lopsided districts should pull people off median but clearly there's more going on than median targeting
  + Is there evidence that ideological positions are explained by party-public ideology?
- Core empirical questions:
  + given that party-public ideology ≠ presidential vote, are candidates positioning themselves relative to party-public ideology in an empirically demonstrable way?
  + as a party-public becomes more extreme, are voters more likely to select the extreme candidate?
  + non-direct tests in the literature, stuff that gets close can't really detect a signal
  + seems like there's work going around that's supposing that these ideas are substantiated but I'm wondering if they really are
- mapping onto your work
  + non-ideological model of candidate selection
  + what are the big lessons
  + what are the exposed assumptions of implications of your work




- About your own work:
  + How is polarization *over time* dynamically justified by these models?
    * we see divergence *and* more informative party labels? Or are the labels less informative?
  + Are the parties different? 
    * Are Democrats moderate and high sigma, while Republicans are extreme and low sigma?
  + If we're interested in falsifying critical assumptions, where would we focus?
- Publication of formal work
  + I'm concerned about certain biases in what kind of thing people find "valuable"
  + Formal papers are beneficial for laying out the assumptions of a theory and deriving predictions when you modify parameters
  + but what happens if the intuition is simple or there is no "counter-intuitive" equilibrium. Do reviewers hate it? Does it create incentives for formal theory that is answering questions that people don't ask?
- About my work:
  + Brady, Han, Pope: extremity is rewarded in primaries, primary losers more moderate (DV = primary vote)
  + Hirano, Snyder, Ansolabehere, Hansen: Primary "threat" not strongly related to more extremity (DV = Nominate)




# 5. Choice








# Redistricting chapter

McCarty et al, geography, uncertainty, and polarization

- empirically:
  + R and D legislators vote more differently in districts with similar medians but more inter-party differences
  + heterogeneous preferences measured by ideal point variance within district?
  + model: ideal points are more extreme when the variance around the median increases
- interpretation:
  + seems like a fancy way of saying that there is more legislative polarization in states where Republican and Democratic voters are more different
  + but first looks at "heterogeneity" measure are still weighted by the distribution of partisanship (urban core and rural outlands are "most homogeneous," but we don't know the distance between D and R means)
  + "moderate but heterogeneous" sounds like "leapfrog," but are there moderate legislators where the *parties* are moderate?.
  + Homogeneous but extreme districts are somewhat proxies for the party mean
  + still a story of general election, positioning

Hill and Tausanovich, disconnect




Hill and Tausanovich, primary electorates

- mass polarization in primaries 
- sorting of primary voters into the 'correct' party




Mccarty et al. Gerrymandering

- Difference in party thetas reflects sorting and polarization on fixed characteristics.
  + fixed = AIDD, not gerrymandering
  + over-time increase in sorting effects indicative of selection process facilitated by redistricting
  + the difference attributable to district should increase over time
- Identification
  + they can only pull apart over-time trends because they compare congresses with and without reapportionment between them



# Problems to address

## Is Ideology Meaningful?

Marble and Tyler: trusting ideal points from surveys

- multinomial logit 
- Cross-validation: maybe not respecting the item parameters?
- Find decent relationship to presidential vote 
    - that covers me a little bit: even if theta not good at predicting held-out issue, should still be related to voting, no?
- Groups are more precise than individuals
    - fewer parameters, less individual noise
    - just need to know that partisans _on average_ have meaningful relationships


 

# Ideas

Does poor incumbent performance (X) increase future primary challenges (Y)

- Clinton Republicans in California
- RDD: barely winning -> more challengers


Does extremism of party-publics decrease the between-year-swing?
